# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sachin

"""Service registry constants — maps service names to module/class paths.

Separated from ``__runtime__.py`` so the registry is testable without
instantiating the full Runtime.
"""

from __future__ import annotations

from underwrite.message import Type

__all__ = [
    "HANDLER_CLASSES",
    "HANDLER_MAP",
    "WIRING",
]

# Maps service name -> (module_path, class_name)
HANDLER_MAP: dict[str, str] = {
    "mechanism": "underwrite.services.mechanism",
    "audit": "underwrite.services.audit",
    "quote": "underwrite.services.quote",
    "risk": "underwrite.services.risk",
    "fraud": "underwrite.services.fraud",
    "compliance": "underwrite.services.compliance",
    "npa": "underwrite.services.npa",
    "collateral": "underwrite.services.collateral",
    "recovery": "underwrite.services.recovery",
    "governance": "underwrite.services.governance",
    "graph": "underwrite.services.graph",
    "identity": "underwrite.services.identity",
    "notification": "underwrite.services.notification",
    "reporting": "underwrite.services.reporting",
    "underwriter": "underwrite.services.underwriter",
    "pricing": "underwrite.services.pricing",
    "document": "underwrite.services.document",
    "disbursement": "underwrite.services.disbursement",
    "collection": "underwrite.services.collection",
    "settlement": "underwrite.services.settlement",
    "origination": "underwrite.services.origination",
    "servicing": "underwrite.services.servicing",
    "payment": "underwrite.services.payment",
    "communication": "underwrite.services.communication",
    "workflow": "underwrite.services.workflow",
    "decision": "underwrite.services.decision",
    "fee": "underwrite.services.fee",
    "statement": "underwrite.services.statement",
    "prepayment": "underwrite.services.prepayment",
    "kfs": "underwrite.services.kfs",
    "razorpay": "underwrite.services.razorpay",
    "consent": "underwrite.services.consent",
    "dsr": "underwrite.services.dsr",
    "credit_bureau": "underwrite.services.credit_bureau",
}

HANDLER_CLASSES: dict[str, str] = {
    "mechanism": "Handler",
    "audit": "Handler",
    "quote": "Handler",
    "risk": "Handler",
    "fraud": "Handler",
    "compliance": "Handler",
    "npa": "Handler",
    "collateral": "Handler",
    "recovery": "Handler",
    "governance": "Handler",
    "graph": "Handler",
    "identity": "Handler",
    "notification": "Handler",
    "reporting": "Handler",
    "underwriter": "Handler",
    "pricing": "Handler",
    "document": "Handler",
    "disbursement": "Handler",
    "collection": "Handler",
    "settlement": "Handler",
    "origination": "Handler",
    "servicing": "Handler",
    "payment": "Handler",
    "communication": "Handler",
    "workflow": "Handler",
    "decision": "Handler",
    "fee": "Handler",
    "statement": "Handler",
    "prepayment": "Handler",
    "kfs": "Handler",
    "razorpay": "Handler",
    "consent": "Handler",
    "dsr": "Handler",
    "credit_bureau": "Handler",
}

WIRING: dict[str, list[str]] = {
    Type.SEED_ADDED.value: ["audit", "origination"],
    Type.USER_ADDED.value: ["audit", "fraud", "compliance", "risk", "origination"],
    Type.LOAN_ORIGINATED.value: [
        "audit",
        "fraud",
        "risk",
        "npa",
        "collateral",
        "collection",
        "servicing",
        "payment",
        "fee",
    ],
    Type.REPAID.value: ["audit", "fraud", "collection", "payment", "servicing"],
    Type.DEFAULT_OCCURRED.value: ["audit", "npa", "collateral", "recovery", "settlement", "workflow"],
    Type.REVOKED.value: ["audit", "graph"],
    Type.QUOTE_CALCULATED.value: ["audit", "pricing"],
    Type.KYC_VERIFIED.value: ["audit", "compliance", "workflow"],
    Type.KYC_REJECTED.value: ["audit", "compliance", "notification", "workflow"],
    Type.AML_CLEARED.value: ["audit", "compliance"],
    Type.AML_FROZEN.value: ["audit", "compliance", "notification"],
    Type.FRAUD_ALERT.value: ["audit", "notification", "decision"],
    Type.WASH_FLAG.value: ["audit", "notification", "decision"],
    Type.VELOCITY_FLAG.value: ["audit", "notification", "decision"],
    Type.RISK_SCORED.value: ["audit", "underwriter", "decision"],
    Type.RISK_EARLY_WARNING.value: ["audit", "notification", "servicing"],
    Type.NPA_BUCKET_CHANGED.value: ["audit", "notification", "collection", "reporting"],
    Type.DLG_TRIGGERED.value: ["audit", "notification", "recovery"],
    Type.SMA_CLASSIFIED.value: ["audit", "notification", "collection"],
    Type.PROVISIONING_COMPUTED.value: ["audit", "reporting", "collection"],
    Type.INCOME_RECOGNITION_SUSPENDED.value: ["audit", "servicing", "notification"],
    Type.COLLATERAL_MARKED.value: ["audit"],
    Type.COLLATERAL_LIQUIDATED.value: ["audit", "settlement"],
    Type.GOVERNANCE_PROPOSAL.value: ["governance"],
    Type.GOVERNANCE_EXECUTED.value: ["audit", "governance"],
    Type.RECOVERY_STARTED.value: ["audit", "workflow"],
    Type.RECOVERY_COMPLETED.value: ["audit", "settlement"],
    Type.IDENTITY_REGISTERED.value: ["audit", "identity"],
    Type.IDENTITY_ROTATED.value: ["audit", "identity"],
    Type.NOTIFICATION_SENT.value: ["audit", "communication"],
    Type.REPORT_GENERATED.value: ["audit", "reporting"],
    Type.UNDERWRITER_APPROVED.value: ["audit", "document", "disbursement", "workflow"],
    Type.UNDERWRITER_REJECTED.value: ["audit", "notification", "workflow"],
    Type.UNDERWRITER_CONDITIONAL_APPROVED.value: ["audit", "notification", "workflow"],
    Type.UNDERWRITER_REVIEW.value: ["audit", "notification", "workflow"],
    Type.UNDERWRITER_ESCALATED.value: ["audit", "notification", "workflow"],
    Type.UNDERWRITE_RULE_VIOLATED.value: ["audit", "notification"],
    Type.PRICING_COMPUTED.value: ["audit", "quote", "document"],
    Type.DOCUMENT_GENERATED.value: ["audit", "disbursement", "communication"],
    Type.DISBURSEMENT_PROCESSED.value: ["audit", "servicing"],
    Type.COLLECTION_UPDATED.value: ["audit", "statement", "fee"],
    Type.SETTLEMENT_COMPLETED.value: ["audit", "servicing", "reporting"],
    Type.ORIGINATION_CREATED.value: ["audit", "underwriter", "workflow"],
    Type.ORIGINATION_SUBMITTED.value: ["audit", "risk", "fraud", "compliance"],
    Type.PAYMENT_RECEIVED.value: ["audit", "collection", "servicing", "statement"],
    Type.PAYMENT_DUE.value: ["audit", "notification", "communication"],
    Type.PAYMENT_OVERDUE.value: ["audit", "collection", "fee", "npa", "notification"],
    Type.FEE_ASSESSED.value: ["audit", "statement"],
    Type.PENAL_INTEREST_ASSESSED.value: ["audit", "fee", "statement"],
    Type.PREPAYMENT_REQUEST.value: ["audit", "prepayment"],
    Type.PREPAYMENT_PROCESSED.value: ["audit", "servicing", "payment", "collection", "statement"],
    Type.FORECLOSURE_COMPUTED.value: ["audit", "prepayment", "statement"],
    Type.KFS_GENERATE.value: ["audit", "kfs"],
    Type.KFS_GENERATED.value: ["audit", "communication", "document"],
    Type.STATEMENT_GENERATED.value: ["audit", "communication"],
    Type.RAZORPAY_ORDER_CREATE.value: ["audit", "razorpay"],
    Type.RAZORPAY_ORDER_CREATED.value: ["audit", "payment", "servicing"],
    Type.RAZORPAY_SUBSCRIBE.value: ["audit", "razorpay"],
    Type.RAZORPAY_PAYMENT_CAPTURED.value: ["audit", "payment", "servicing", "collection", "notification"],
    Type.RAZORPAY_PAYMENT_FAILED.value: ["audit", "notification"],
    Type.RAZORPAY_PAYMENT_REFUNDED.value: ["audit", "payment", "servicing"],
    Type.RAZORPAY_SUBSCRIPTION_CREATED.value: ["audit", "notification"],
    Type.RAZORPAY_SUBSCRIPTION_CHARGED.value: ["audit", "payment", "servicing", "collection"],
    Type.RAZORPAY_SUBSCRIPTION_FAILED.value: ["audit", "notification"],
    Type.RAZORPAY_MANDATE_ACTIVE.value: ["audit", "servicing", "notification"],
    Type.RAZORPAY_MANDATE_INACTIVE.value: ["audit", "notification"],
    Type.RAZORPAY_WEBHOOK_RECEIVED.value: ["audit", "razorpay"],
    Type.CONSENT_RECORDED.value: ["audit", "consent"],
    Type.CONSENT_WITHDRAWN.value: ["audit", "consent"],
    Type.CONSENT_EXPIRED.value: ["audit", "consent", "notification"],
    Type.DSR_REQUEST.value: ["audit", "dsr"],
    Type.DSR_REQUESTED.value: ["audit", "notification"],
    Type.DSR_FULFILLED.value: ["audit", "dsr", "notification"],
    Type.DSR_REJECTED.value: ["audit", "dsr", "notification"],
    Type.GRIEVANCE_LOGGED.value: ["audit", "dsr"],
    Type.GRIEVANCE_RESOLVED.value: ["audit", "dsr", "notification"],
    Type.BREACH_DETECTED.value: ["audit", "dsr", "notification"],
    Type.BREACH_NOTIFIED.value: ["audit", "notification"],
    Type.BREACH_CLOSED.value: ["audit", "dsr"],
    Type.DATA_PURGED.value: ["audit", "dsr"],
    Type.DATA_ARCHIVED.value: ["audit", "dsr"],
    Type.WORKFLOW_STARTED.value: ["audit"],
    Type.WORKFLOW_COMPLETED.value: ["audit", "notification"],
    Type.DECISION_MADE.value: ["audit", "underwriter", "workflow"],
    Type.CREDIT_BUREAU_CHECK.value: ["audit", "credit_bureau"],
    Type.CREDIT_BUREAU_CHECKED.value: ["audit", "underwriter", "notification"],
    Type.CREDIT_BUREAU_CHECK_FAILED.value: ["audit", "notification"],
    Type.CKYC_VERIFY.value: ["audit", "credit_bureau"],
    Type.CKYC_VERIFIED.value: ["audit", "compliance", "notification", "workflow"],
    Type.CKYC_REJECTED.value: ["audit", "compliance", "notification", "workflow"],
    # Compliance — video KYC, AML risk levels
    Type.AML_FLAGGED.value: ["audit", "compliance", "notification", "decision"],
    Type.KYC_VIDEO_INITIATED.value: ["audit", "compliance", "notification"],
    Type.KYC_VIDEO_VERIFIED.value: ["audit", "compliance", "workflow"],
    # Pricing — penal interest, foreclosure
    Type.PRICING_PENAL_INTEREST.value: ["audit", "pricing"],
    Type.PRICING_PENAL_INTEREST_COMPUTED.value: ["audit", "fee", "collection", "statement"],
    Type.PRICING_FORECLOSURE.value: ["audit", "pricing"],
    Type.PRICING_FORECLOSURE_COMPUTED.value: ["audit", "prepayment", "settlement"],
    # Recovery — progress events
    Type.RECOVERY_OFFER.value: ["audit", "communication", "notification"],
    Type.RECOVERY_OFFER_RESPONSE.value: ["audit", "recovery"],
    Type.RECOVERY_ESCALATED.value: ["audit", "notification", "collection"],
    Type.RECOVERY_PROGRESS.value: ["audit", "collection", "statement"],
}
