"""Package version, sourced from ``_version.py`` (generated by setuptools-scm)."""

try:
    from underwrite._version import __version__ as _v  # type: ignore[assignment]
    from underwrite._version import __version_tuple__ as _vt
    __version__: str = _v
    __version_tuple__: tuple[int, ...] = _vt
except ImportError:
    __version__ = "0.0.0"
    __version_tuple__ = (0, 0, 0)

__all__ = [
    "__version__",
    "__version_tuple__",
]
