#!/usr/bin/env bash
#
# cleanup.sh — Remove all build/test artifacts from the project.
#
set -euo pipefail
shopt -s globstar

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

echo "==> Removing __pycache__ directories..."
find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

echo "==> Removing .pyc files..."
find . -name "*.pyc" -delete 2>/dev/null || true

echo "==> Removing .pyo files..."
find . -name "*.pyo" -delete 2>/dev/null || true

echo "==> Removing build artifacts..."
rm -rf build/ dist/ *.egg-info .eggs 2>/dev/null || true

echo "==> Removing pytest cache, .benchmarks, and coverage data..."
rm -rf .pytest_cache .benchmarks .coverage coverage* htmlcov 2>/dev/null || true

echo "==> Removing mypy cache..."
rm -rf .mypy_cache .mypy* 2>/dev/null || true

echo "==> Removing ruff cache..."
rm -rf .ruff_cache 2>/dev/null || true

echo "==> Removing mutmut cache..."
rm -rf .mutmut* 2>/dev/null || true

echo "==> Removing .tox environment..."
rm -rf .tox 2>/dev/null || true

echo "==> Removing .venv (if present)..."
rm -rf .venv 2>/dev/null || true

echo "==> Removing Docker artifacts..."
rm -f underwrite-*.tar 2>/dev/null || true

echo "==> Removing __version__.py (regenerated by setuptools-scm)..."
rm -f underwrite/__version__.py 2>/dev/null || true

echo "==> Cleanup complete."
