"""Generate a minimal Python SDK from a FastAPI OpenAPI JSON spec.

Item 67 from production roadmap.

Usage:
    python scripts/generate_sdk.py --input openapi.json --output sdk/ulu_client.py
    python scripts/generate_sdk.py --url http://localhost:8000/openapi.json --output sdk/ulu_client.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import jinja2


def _to_snake(path: str) -> str:
    """Converts a path like /v1/seed/create to v1_seed_create."""
    return re.sub(r"[^a-zA-Z0-9]+", "_", path.strip("/")).strip("_")


def _python_type(schema: dict) -> str:
    """Maps simple OpenAPI schema types to Python type hints."""
    t = schema.get("type", "Any")
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        items = schema.get("items", {})
        return f"list[{_python_type(items)}]"
    if t == "object":
        return "dict[str, Any]"
    return "Any"


def _build_methods(spec: dict) -> list[dict]:
    """Extracts operations from the OpenAPI paths."""
    methods = []
    paths = spec.get("paths", {})
    for path, ops in paths.items():
        for method, details in ops.items():
            if method == "parameters":
                continue
            name = details.get("operationId") or f"{method}_{_to_snake(path)}"
            # sanitize name
            name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
            params = []
            body_schema = None
            for param in details.get("parameters", []):
                params.append(
                    {
                        "name": param["name"],
                        "py_type": _python_type(param.get("schema", {})),
                        "required": param.get("required", False),
                        "in": param.get("in", "query"),
                    }
                )
            if "requestBody" in details:
                content = details["requestBody"].get("content", {})
                if "application/json" in content:
                    body_schema = content["application/json"].get("schema", {})
            methods.append(
                {
                    "name": name,
                    "method": method.upper(),
                    "path": path,
                    "params": params,
                    "body_schema": body_schema,
                    "summary": details.get("summary", ""),
                }
            )
    return methods


_TEMPLATE = '''"""Auto-generated ULU Python SDK.

Generated by scripts/generate_sdk.py — do not edit manually.
"""

from __future__ import annotations

from typing import Any

import httpx


class UluClient:
    """Minimal HTTP client for the ULU API."""

    def __init__(self, base_url: str = "http://localhost:8000", timeout: float = 30.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self._client = httpx.Client(timeout=timeout)

    def _request(self, method: str, path: str, *, params: dict[str, Any] | None = None, json: Any = None) -> Any:
        url = self.base_url + path
        response = self._client.request(method, url, params=params, json=json)
        response.raise_for_status()
        return response.json()

    {% for m in methods %}
    def {{ m.name }}(
        self
        {%- for p in m.params %}, {{ p.name }}: {{ p.py_type }}{% if not p.required %} | None = None{% endif %}\
{% endfor %}
        {%- if m.body_schema %}, body: dict[str, Any]{% endif %}
    ) -> Any:
        """{{ m.summary }}"""
        params = {}
        {% for p in m.params %}{% if p.in == 'query' %}
        if {{ p.name }} is not None:
            params["{{ p.name }}"] = {{ p.name }}
        {% endif %}{% endfor %}
        path = "{{ m.path }}"
        {% for p in m.params %}{% if p.in == 'path' %}
        path = path.replace("{{ '{' + p.name + '}' }}", str({{ p.name }}))
        {% endif %}{% endfor %}
        return self._request("{{ m.method }}", path, params=params{% if m.body_schema %}, json=body{% endif %})
    {% endfor %}

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "UluClient":
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()
'''


def generate(spec: dict) -> str:
    methods = _build_methods(spec)
    template = jinja2.Template(_TEMPLATE, trim_blocks=True, lstrip_blocks=True)
    return template.render(methods=methods)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate ULU Python SDK from OpenAPI spec")
    parser.add_argument("--input", type=Path, help="Path to openapi.json file")
    parser.add_argument("--url", type=str, help="URL to fetch openapi.json from")
    parser.add_argument("--output", type=Path, required=True, help="Output Python file path")
    args = parser.parse_args()

    if args.input:
        spec = json.loads(args.input.read_text(encoding="utf-8"))
    elif args.url:
        import urllib.request

        with urllib.request.urlopen(args.url, timeout=30) as resp:  # noqa: S310
            spec = json.loads(resp.read().decode("utf-8"))
    else:
        parser.error("Provide either --input or --url")
        return 1

    code = generate(spec)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(code, encoding="utf-8")
    print(f"SDK written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
